### ISSUE TITLE
Do not copy matrix directories in each module

### ISSUE THREAD

**Issue by andpet0101** [dcgc-bfx/scrnaseq2#35]
When using on-disk matrices, we copy these directories twice:

- at the beginning to a fast `/tmp` SSD for performance
- at the end to the project module directory slow server

The first copy is usually fast, the second takes much longer. But if we do not modify the matrix directories, the second step might not be necessary. It could be enough if we keep them in the normalization module?

**Comment by ktrns** [comment]
two considerations:
- fast reading from SSD for calculation
- writing only for modules that actually change something
