### ISSUE TITLE
Chapter "Cluster Annotation" finish up 

### ISSUE THREAD

**Issue by ktrns** [dcgc-bfx/scrnaseq2#9]
Add module `cluster_annotation`
- Marker genes
- Genes of interest

**Comment by ktrns** [comment]
PR #30 

Still missing: 
- heatmap 
- functional enrichment analysis of markers

**Comment by ktrns** [comment]
- RG build some gsea functions and plots - find a way to incorporate this

**Comment by rajinder4489** [comment]
Done with commit 707b531b8348f4c7c9f130c3f00e9d8dff1c866b
